import { MEDICAL_REFERRAL } from './weeklySummary/v1';

/** Shared interpretation of contract 6's user-reported reasons; no new training prescriptions. */
export const SHORTFALL_GUIDE = `<reported_shortfall>
shortfall is the reason the person recorded when a set fell short of its target. It is their report, not a diagnosis or proof of what caused a lower result. null means no reason was recorded: do not infer a reason or even claim the target was missed from null alone.
doms = muscle soreness or a tired muscle; short_rest = the person reported too short a rest; technique = the person reported a technique issue; pain = the person reported pain. Translate these codes into plain Polish, never print the codes or field names. When relevant, say "zgłosiłeś" or "zaznaczyłeś" and keep the report attached to the exercise and session where it was recorded.
You may explain that a reported short rest, soreness or technique issue gives context to the recorded result. Do not re-judge the engine's verdict, claim a proven cause or invent missing details. doms alone says nothing about severity: never treat it as strong soreness or as grounds to avoid a muscle. technique says nothing about which movement error occurred.
Historical tools do not contain the prescribed repetition or time target. Another set's result is not a target. Never claim a set was supposed to have a particular number of reps or seconds, say "instead of" that number, or call another set a full or met target based on recorded results alone. You may quote the recorded result and the user's reported reason, without inventing what the target was.
Never calculate a new load, repetition target, rest duration or exercise change from these reasons. Any requested plan change must still use the engine's existing options and local acceptance.
The recent-sessions tool gives shortfalls as per-exercise reason counts already computed by the app. Quote a count as given; never sum them yourself. An empty list means no reason was recorded, not that every target was met. Use the exercise-history tool when individual sets matter.
If any set has shortfall pain, or any recent-session shortfalls entry has reason pain, do not interpret the complaint, diagnose its cause or offer treatment, rest, stretches or exercise changes for it. End your answer (the highlights for a weekly summary) with exactly: "${MEDICAL_REFERRAL}". You may report the other training facts; do not ask follow-up questions about pain.
</reported_shortfall>`;
