import type { ExclusionCode } from '@/domain/exercises/screen';
import type {
  BandSuitability,
  Equipment,
  MovementPattern,
  MuscleGroup,
  Plane,
  Stance,
} from '@/domain/types';

/**
 * All user-facing copy lives here. The app is Polish-only by design
 * (single user), but keeping strings in one module means the UI code
 * stays free of hardcoded text and copy can be reviewed in one place.
 */
export const pl = {
  tabs: {
    today: 'Dziś',
    workout: 'Trening',
    body: 'Ciało',
    history: 'Historia',
    more: 'Więcej',
  },
  today: {
    title: 'Dziś',
    weightCard: 'Waga',
    noWeightYet: 'Jeszcze się nie ważyłeś.',
    logWeightToday: 'Zapisz dzisiejszą wagę',
    weightLoggedToday: (kg: number) => `Dziś: ${kg} kg`,
    average7: (kg: number) => `śr. 7 dni: ${kg} kg`,
    trend: (kgPerWeek: number) =>
      kgPerWeek === 0
        ? 'trend: stabilnie'
        : `trend: ${kgPerWeek > 0 ? '+' : ''}${kgPerWeek} kg/tydz.`,
    sessionCard: 'Trening',
    nextTemplate: (name: string) => `Następny: ${name}`,
    startNext: (name: string) => `Rozpocznij ${name}`,
    dailyCard: 'Dziennik dnia',
    dailyEmpty: 'Jak się dziś czujesz? Sen, energia, zakwasy — 10 sekund.',
    dailySummary: (sleep: number | null, energy: number | null, soreCount: number) =>
      [
        sleep !== null ? `sen ${sleep} h` : null,
        energy !== null ? `energia ${energy}/5` : null,
        soreCount > 0 ? `zakwasy: ${soreCount}` : null,
      ]
        .filter(Boolean)
        .join(' · ') || 'Wpis zapisany.',
    fillDaily: 'Uzupełnij',
    editDaily: 'Edytuj',
  },
  workout: {
    title: 'Trening',
    resumeBanner: (templateName: string) => `Niedokończona sesja: ${templateName}`,
    resume: 'Wznów',
    discard: 'Porzuć',
    discardConfirmTitle: 'Porzucić sesję?',
    discardConfirmBody:
      'Zalogowane serie zostaną w historii jako sesja porzucona. Nie da się jej potem wznowić.',
    blockCount: (n: number) => `${n} ${n === 1 ? 'blok' : n >= 2 && n <= 4 ? 'bloki' : 'bloków'}`,
    start: 'Rozpocznij',
    suggested: 'Sugerowane',
    lastSession: (daysAgo: number) =>
      daysAgo === 0
        ? 'Ostatnia sesja: dziś'
        : daysAgo === 1
          ? 'Ostatnia sesja: wczoraj'
          : `Ostatnia sesja: ${daysAgo} dni temu`,
    noSessionsYet: 'Brak sesji w historii — zacznij od dowolnego szablonu.',
    quickCardio: 'Szybki log: rower',
    session: {
      setOf: (n: number, total: number) => `seria ${n} / ${total}`,
      dumbbellSingle: 'Hantel (jeden gryf)',
      dumbbellPaired: 'Hantle (para)',
      band: 'Guma',
      anchorPosition: 'Pozycja',
      reps: 'Powtórzenia',
      time: 'Czas',
      saveSet: 'Zapisz serię',
      restLabel: 'Przerwa',
      restExtend: '+30 s',
      restSkip: 'Pomiń',
      restNotificationBody: 'Wracaj do treningu — czas na kolejną serię.',
      upNext: 'Następne',
      warmupTitle: 'Rozgrzewka',
      warmupDescription: 'Kilka minut na rowerze przed pierwszą serią.',
      minutes: 'Minuty',
      warmupLog: 'Zapisano, zaczynamy',
      warmupSkip: 'Pomiń rozgrzewkę',
      substituteTitle: 'Zamień ćwiczenie',
      noSubstitutes: 'Brak dostępnych zamienników dla Twojego profilu.',
      progressTitle: 'Postęp sesji',
      finishEarly: 'Zakończ',
      notFound: 'Nie znaleziono treningu.',
    },
    summary: {
      title: 'Podsumowanie',
      setsLogged: (n: number) => `${n} ${n === 1 ? 'seria' : 'serii'} zalogowanych`,
      previousComparison: (daysAgo: number, previousSets: number, currentSets: number) =>
        `Poprzednia sesja tego szablonu: ${daysAgo} ${daysAgo === 1 ? 'dzień' : 'dni'} temu, ${previousSets} serii (dziś: ${currentSets}).`,
      noPrevious: 'To pierwsza sesja tego szablonu w historii.',
      sessionRpe: 'Jak ciężko było całościowo? (RPE)',
      notes: 'Notatka (opcjonalnie)',
      notesPlaceholder: 'Coś ważnego z dzisiejszej sesji…',
      finish: 'Zakończ trening',
    },
  },
  body: {
    title: 'Ciało',
    weightSection: 'Waga',
    weightInputLabel: 'Dzisiejsza waga (kg)',
    weightSave: 'Zapisz',
    weightSavedToday: 'Zapisano na dziś. Możesz poprawić — nadpisze wpis.',
    chartTitle: 'Ostatnie 60 dni',
    chartLegend: 'kropki = wpisy · linia = średnia 7-dniowa',
    chartEmpty: 'Wykres pojawi się po 3 wpisach.',
    noTrendYet: 'Trend pojawi się po ~10 wpisach w ciągu 3 tygodni.',
    measurementsLink: 'Obwody',
    measurementsHint: 'Talia, biodra, klatka, ramię, udo, szyja',
    dailyLink: 'Dziennik dnia',
    dailyHint: 'Sen, energia, stres, zakwasy',
    invalidWeight: 'Podaj wagę między 30 a 300 kg.',
  },
  measurements: {
    title: 'Obwody',
    intro: 'Mierz zawsze tak samo: rano, na czczo, taśma płasko, bez wciągania brzucha.',
    waist: 'Talia (cm)',
    hips: 'Biodra (cm)',
    chest: 'Klatka (cm)',
    arm: 'Ramię (cm)',
    thigh: 'Udo (cm)',
    neck: 'Szyja (cm)',
    save: 'Zapisz obwody',
    saved: 'Zapisano.',
    lastEntry: (date: string) => `Ostatni pomiar: ${date}`,
    navyTitle: 'Szacowany % tkanki tłuszczowej (wzór US Navy)',
    navyValue: (pct: number) => `≈ ${pct} %`,
    navyMissingProfile: 'Uzupełnij wzrost i płeć w Ustawieniach, żeby policzyć.',
    navyMissingInputs: 'Potrzebne: talia, szyja (i biodra dla kobiet).',
    navyCaveat: '±3–4 p.p. Patrz na trend, nie na liczbę.',
    waistChartTitle: 'Talia — ostatnie 90 dni',
    waistChartEmpty: 'Wykres talii pojawi się po 2 pomiarach.',
    invalid: 'Wartości muszą być między 20 a 250 cm.',
  },
  daily: {
    title: 'Dziennik dnia',
    sleep: 'Sen (godziny)',
    energy: 'Energia',
    stress: 'Stres',
    soreness: 'Zakwasy (DOMS)',
    sorenessHint: 'Stuknij: brak → lekkie → mocne.',
    sorenessMild: 'lekko',
    sorenessStrong: 'mocno',
    note: 'Notatka',
    notePlaceholder: 'Cokolwiek istotnego…',
    save: 'Zapisz',
    saved: 'Zapisano.',
    scaleLow: '1 = fatalnie',
    scaleHigh: '5 = świetnie',
    stressLow: '1 = spokój',
    stressHigh: '5 = ciężko',
  },
  settings: {
    title: 'Ustawienia',
    profileSection: 'Profil',
    heightCm: 'Wzrost (cm)',
    birthYear: 'Rok urodzenia',
    sex: 'Płeć',
    sexMale: 'mężczyzna',
    sexFemale: 'kobieta',
    dayBoundaryHour: 'Granica doby treningowej (godzina)',
    dayBoundaryHint: 'Trening o 00:40 przy granicy 4:00 liczy się do poprzedniego dnia.',
    saddleHeightCm: 'Wysokość siodełka (cm)',
    saddleHint: 'Ustaw raz i nie zmieniaj — ma znaczenie dla kolana.',
    kneeSection: 'Profil kolana',
    physioApproved: 'Lista ćwiczeń zaakceptowana przez fizjoterapeutę',
    physioApprovedHint:
      'Odblokowuje ćwiczenia jednonóż z podparciem (split squat, wykrok w tył, wejście na stopień, kickback). Włącz dopiero po realnej konsultacji.',
    remindersSection: 'Przypomnienia',
    weightReminder: 'Waga codziennie',
    workoutReminder: 'Trening, gdy minie',
    afterDays: (n: number) => `${n} ${n === 1 ? 'dzień' : 'dni'}`,
    time: 'o godzinie',
    muteWeek: 'Wycisz na 7 dni',
    mutedUntil: (date: string) => `Wyciszone do ${date}`,
    unmute: 'Włącz z powrotem',
    save: 'Zapisz ustawienia',
    saved: 'Zapisano.',
    invalidProfile: 'Sprawdź wartości: wzrost 100–250, rok 1900–2020, godzina 0–23.',
  },
  reminders: {
    weightTitle: 'Waga',
    weightBody: 'Zważ się, zanim zjesz — jeden wpis, 10 sekund.',
    workoutTitle: 'Trening',
    workoutBody: (daysAgo: number) =>
      `Ostatni trening był ${daysAgo} ${daysAgo === 1 ? 'dzień' : 'dni'} temu. Kolejna sesja czeka, kiedy będziesz gotowy.`,
  },
  history: {
    title: 'Historia',
  },
  more: {
    title: 'Więcej',
    exercises: 'Ćwiczenia',
    bands: 'Gumy',
    templates: 'Szablony',
    backup: 'Eksport / Import',
    settings: 'Ustawienia',
    comingSoon: 'Gumy, szablony i backup dojdą w następnych kamieniach.',
  },
  exercises: {
    title: 'Ćwiczenia',
    empty: 'Baza ćwiczeń jest pusta.',
    countLabel: (n: number, excluded: number) =>
      `${n} ${n === 1 ? 'ćwiczenie' : 'ćwiczeń'} w bazie` +
      (excluded > 0 ? ` · ${excluded} wykluczone dla Twojego profilu` : ''),
    kneeFlag: 'Obciąża kolano',
    excluded: 'Wykluczone',
    pendingPhysio: 'Po akceptacji fizjoterapeuty',
    sections: {
      cues: 'Jak wykonać',
      kneeCue: 'Kolano',
      muscles: 'Partie mięśniowe',
      primary: 'główne',
      secondary: 'pomocnicze',
      equipment: 'Sprzęt',
      biomechanics: 'Biomechanika',
      substitutes: 'Zamienniki',
      whyExcluded: 'Dlaczego wykluczone',
      noMedia: 'Brak zdjęcia — opis poniżej.',
    },
    biomechanics: {
      pattern: 'Wzorzec',
      planes: 'Płaszczyzny',
      chain: 'Łańcuch',
      closedChain: 'zamknięty',
      openChain: 'otwarty',
      stance: 'Podparcie',
      bandFit: 'Dopasowanie gumy',
    },
  },
  labels: {
    pattern: {
      Squat: 'Przysiad',
      Hinge: 'Zawias biodrowy',
      Lunge: 'Wykrok',
      Push: 'Pchanie',
      Pull: 'Przyciąganie',
      Carry: 'Noszenie',
      Isolation: 'Izolacja',
      Core: 'Core',
      Cardio: 'Cardio',
      Mobility: 'Mobilność',
    } satisfies Record<MovementPattern, string>,
    muscle: {
      quads: 'czworogłowe',
      hamstrings: 'dwugłowe uda',
      glutes: 'pośladki',
      calves: 'łydki',
      chest: 'klatka',
      back: 'plecy',
      lats: 'najszersze',
      shoulders: 'barki',
      biceps: 'biceps',
      triceps: 'triceps',
      core: 'core',
      forearms: 'przedramiona',
    } satisfies Record<MuscleGroup, string>,
    equipment: {
      dumbbell: 'hantle',
      band: 'guma',
      mat: 'karimata',
      bike: 'rower',
      bodyweight: 'masa ciała',
    } satisfies Record<Equipment, string>,
    plane: {
      Sagittal: 'strzałkowa',
      Frontal: 'czołowa',
      Transverse: 'poprzeczna',
    } satisfies Record<Plane, string>,
    stance: {
      Bilateral: 'obunóż',
      UnilateralSupported: 'jednonóż z podparciem',
      UnilateralUnsupported: 'jednonóż bez podparcia',
      Seated: 'siedząc',
      Prone: 'w podporze / na brzuchu',
      Supine: 'na plecach',
    } satisfies Record<Stance, string>,
    bandSuitability: {
      excellent: 'świetne — opór rośnie tam, gdzie jesteś najsilniejszy',
      ok: 'neutralne',
      poor: 'słabe — guma jest najcięższa w najsłabszym punkcie',
    } satisfies Record<BandSuitability, string>,
    dumbbellMode: {
      paired: 'dwa hantle (do 10 kg na rękę)',
      single: 'jeden hantel (do 18 kg)',
    },
  },
  exclusion: {
    KNEE_FRONTAL_PLANE:
      'Ruch w płaszczyźnie czołowej obciąża kolano bocznie — brak więzadeł pobocznych tego nie zatrzyma.',
    KNEE_TRANSVERSE_PLANE:
      'Rotacja pod obciążeniem tworzy moment skrętny na przeszczep ACL bez wsparcia stabilizatorów bocznych.',
    KNEE_VALGUS_VARUS: 'Ćwiczenie wprost prowokuje ucieczkę kolana do wewnątrz lub na zewnątrz.',
    KNEE_UNILATERAL_UNSUPPORTED:
      'Cała masa na jednej nodze bez podparcia — ekstremalne zapotrzebowanie na stabilizację, której kolano nie ma pasywnie.',
    KNEE_UNILATERAL_PENDING_PHYSIO:
      'Praca jednonóż z podparciem. Odblokuje się po akceptacji listy przez fizjoterapeutę (Ustawienia → profil kolana).',
    KNEE_PLYOMETRIC:
      'Wyskoki i lądowania wielokrotnie zwiększają siły ścinające na zrekonstruowane struktury.',
    KNEE_OPEN_CHAIN_QUAD:
      'Otwarty łańcuch na czworogłowy: maksymalna przednia siła ścinająca na przeszczep ACL w zakresie 0–30°, bez ko-kontrakcji dwugłowych.',
  } satisfies Record<ExclusionCode, string>,
  common: {
    loading: 'Ładowanie…',
    error: 'Coś poszło nie tak.',
    notFound: 'Nie znaleziono.',
    cancel: 'Anuluj',
    today: 'dziś',
    yesterday: 'wczoraj',
  },
} as const;
