/**
 * Pulls demonstration frames for the exercise catalogue from free-exercise-db.
 *
 * free-exercise-db (github.com/yuhonas/free-exercise-db) is public domain
 * under The Unlicense, so the frames can be vendored into the repo outright.
 * Only the exercises listed in data/media-sources.json are fetched — there
 * is no reason to clone 800+ exercises for the ~40 this app uses.
 *
 * Each source exercise has two frames (start / end of movement). They are
 * stored as assets/exercise-media/<our-id>-0.jpg and -1.jpg, and a typed
 * require() map is regenerated at src/assets/exercise-media.ts because Metro
 * cannot resolve image paths built at runtime.
 *
 * Usage: npm run media:import [-- --force]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(__dirname, '..');
const MEDIA_DIR = join(ROOT, 'assets', 'exercise-media');
const MAP_FILE = join(ROOT, 'src', 'assets', 'exercise-media.ts');
const SOURCES_FILE = join(ROOT, 'data', 'media-sources.json');
const RAW_BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';
const FRAMES = [0, 1] as const;

const force = process.argv.includes('--force');

type Sources = Record<string, string>;

async function download(url: string, target: string): Promise<boolean> {
  const res = await fetch(url);
  if (res.status === 404) return false;
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  writeFileSync(target, Buffer.from(await res.arrayBuffer()));
  return true;
}

function writeLicense(): void {
  writeFileSync(
    join(MEDIA_DIR, 'LICENSE'),
    [
      'The images in this directory originate from free-exercise-db',
      '(https://github.com/yuhonas/free-exercise-db) and are released into',
      'the public domain under The Unlicense.',
      '',
      'This is free and unencumbered software released into the public domain.',
      '',
      'Anyone is free to copy, modify, publish, use, compile, sell, or',
      'distribute this software, either in source code form or as a compiled',
      'binary, for any purpose, commercial or non-commercial, and by any',
      'means.',
      '',
      'For more information, please refer to <https://unlicense.org>',
      '',
      "The mapping from this project's exercise ids to the source exercises",
      'is kept in data/media-sources.json.',
      '',
    ].join('\n'),
  );
}

function writeRequireMap(ids: string[], framesById: Map<string, number[]>): void {
  const lines = [
    '// GENERATED by scripts/import-media.ts — do not edit by hand.',
    '// Metro needs static require() calls; it cannot resolve image paths built at runtime.',
    '',
    "import type { ImageSourcePropType } from 'react-native';",
    '',
    'export const exerciseMedia: Record<string, ImageSourcePropType[]> = {',
  ];

  for (const id of ids) {
    const frames = framesById.get(id) ?? [];
    if (frames.length === 0) continue;
    const requires = frames
      .map((f) => `require('../../assets/exercise-media/${id}-${f}.jpg')`)
      .join(', ');
    lines.push(`  '${id}': [${requires}],`);
  }

  lines.push('};', '');
  mkdirSync(join(ROOT, 'src', 'assets'), { recursive: true });
  writeFileSync(MAP_FILE, lines.join('\n'));
}

async function main(): Promise<void> {
  const raw = JSON.parse(readFileSync(SOURCES_FILE, 'utf8')) as Sources & { _comment?: string };
  delete raw._comment;
  const sources = raw as Sources;
  const ids = Object.keys(sources).sort();

  mkdirSync(MEDIA_DIR, { recursive: true });

  const framesById = new Map<string, number[]>();
  const missing: string[] = [];
  let fetched = 0;
  let skipped = 0;

  for (const id of ids) {
    const sourceId = sources[id] as string;
    const frames: number[] = [];

    for (const frame of FRAMES) {
      const target = join(MEDIA_DIR, `${id}-${frame}.jpg`);
      if (existsSync(target) && !force) {
        frames.push(frame);
        skipped += 1;
        continue;
      }
      const ok = await download(`${RAW_BASE}/${sourceId}/${frame}.jpg`, target);
      if (ok) {
        frames.push(frame);
        fetched += 1;
      } else if (frame === 0) {
        missing.push(`${id} -> ${sourceId}`);
      }
    }

    framesById.set(id, frames);
    process.stdout.write(`  ${id}: ${frames.length} frame(s)\n`);
  }

  writeLicense();
  writeRequireMap(ids, framesById);

  console.log(
    `\ndone — ${fetched} fetched, ${skipped} already present, map written to ${relative(ROOT, MAP_FILE)}`,
  );

  if (missing.length > 0) {
    console.error('\nsource exercises not found (check data/media-sources.json):');
    for (const m of missing) console.error(`  ${m}`);
    process.exit(1);
  }
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
