/**
 * F1 — the weekly summary (AI-INTEGRACJA §3).
 *
 * `weeklySummarySchema` is what the model is asked to return. Per the
 * schema-writing rules in §4.4 it uses `z.enum` rather than literals, has
 * no field a load could go into (I1), and relies on Zod after parsing —
 * not on the provider — to enforce the length bounds.
 */
import { z } from 'zod';

import { SIGNAL_CODES } from '../../domain/coach/vocabulary';
import { apiErrorSchema, usageSchema } from './api';
import { coachContextSchema } from './coachContext';
import { CONTRACT_VERSION } from './versions';

export const weeklySummarySchema = z.object({
  /** One sentence: where things stand. */
  headline: z.string().min(1).max(160),
  /** What went well or is worth knowing; each point quotes numbers from the context. */
  highlights: z.array(z.string().min(1).max(280)).min(1).max(4),
  /** Comments on the signals the context carries, and only on those. */
  flags: z
    .array(
      z.object({
        code: z.enum(SIGNAL_CODES),
        comment: z.string().min(1).max(280),
      }),
    )
    .max(5),
  /** Things worth asking the user next time. */
  questions: z.array(z.string().min(1).max(200)).max(2),
});

export type WeeklySummary = z.infer<typeof weeklySummarySchema>;

export const weeklySummaryRequestSchema = z.strictObject({
  contractVersion: z.literal(CONTRACT_VERSION),
  /** Generated by the app; echoed in the response and in every log line. */
  requestId: z.string().min(8).max(64),
  context: coachContextSchema,
});

export type WeeklySummaryRequest = z.infer<typeof weeklySummaryRequestSchema>;

/*
 * What the Worker answers: this endpoint's success shape, then the errors
 * every endpoint shares (see api.ts).
 */

export const weeklySummaryOkSchema = z.strictObject({
  kind: z.literal('ok'),
  requestId: z.string(),
  promptVersion: z.string(),
  model: z.string(),
  usage: usageSchema,
  /** `ok_after_repair`: the first answer failed validation and the second passed. */
  validationOutcome: z.enum(['ok', 'ok_after_repair']),
  summary: weeklySummarySchema,
});

export const weeklySummaryResponseSchema = z.discriminatedUnion('kind', [
  weeklySummaryOkSchema,
  ...apiErrorSchema.options,
]);

export { apiErrorSchema, usageSchema, type ApiError } from './api';
export type WeeklySummaryOk = z.infer<typeof weeklySummaryOkSchema>;
export type WeeklySummaryResponse = z.infer<typeof weeklySummaryResponseSchema>;
